language: node_js
node_js:
  - "10"
before_install:
  # Install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
  - yarn build
deploy:
  # Deploy server to heroku
  - provider: heroku
    app: server-tic-tac-toe
    api_key:
      secure: NSNDn7pzypPbX6utGEJgegiFd0jlwgk+Q6nbpEfPvdr75nfXVogItN/O4AEDSh1OsbhCI8+ChN2fRfPtDB1qOCYSVjU66B5scJAfFLcKSbyxbAI7ky6BWuckPg2tjTtttiejEEkm8+xkWOUzLoCYSmSqkEDnuW3BmaQDunXwTrwh1DDRAuKzsFHG60VWJW39Kxxf148MSqYBHEGarddKUbdaOGxNH16X/zYEQzYYm3jWwaRzzu6uAoZbgfTCwWPKSHQCDduYrtTyAL8qM7WHghb5PGx4oz6mdd0jw7fr+mgyRz4u2cN1RmfnQsq1vEmkara65i9bn9vdjRiO68+mELbRgUof7CTNmUzYPyI1hgOQ3O6cE8pGFVzZqF+HqATC7z6nXSE2IX1VzpeKNdBU1SpFTwuMntau0g3i0/X4d2zvgLyFmqgyL0zS5i36xNHsuHPVXcuWJIjgPzT466xocJ+9fgXz5is6R40BrPm7Rzrsqf6M3Hi1vB7I5TD+j8A3y93XQlI4J17Z95hehwQseFKFy6ZcKb7acj1oEWJz1UR2+UBJzQ//EhEP0Qa6HSsZZNWD61A5Vqz4dJNVIxLfiWhS1aA0VLaIpkb3znqWI006TgTmngegU0dtV1x0VPSBYaFdP6KYNK8TUbYetadpHpYrsZqW3s3HQeqBxHk9Rx4=
    skip_cleanup: true
